spring.application.name=parc-applicatif

# Variables d'environnement avec fallback local
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/parc_applicatif}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8081}